framework:
    router:
        strict_requirements: null
        utf8: true


# coop_tilleuls_forgot_password:
#     resource: '@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml'
#     prefix:   '/forgot_password'