easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
    
menu_liste:
    path:          /menu
    controller:    Symfony\Bundle\FrameworkBundle\Controller\MenuController
    defaults:
        # the path of the template to render
        template:  'menu.html.twig'